# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
    -   id: detect-secrets
-   repo: https://github.com/PyCQA/pylint
    rev: v2.16.1
    hooks:
    -   id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
-   repo:  https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.0.0'
    hooks:
    -   id: mypy
        name: mypy
        entry: mypy
        language: system
        types: [python]
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v2.0.1
    hooks:
    -   id: autopep8
        entry: autopep8
        language: system
        types: [python]
